/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface InstantiateMsg {
  initial_amount: Uint128;
  owner: string;
  precision: number;
  subunit: string;
  symbol: string;
}
export type ExecuteMsg = {
  create_asset: {
    asset_type: AssetType;
    price: Uint128;
    total_supply: Uint128;
    uri: string;
  };
} | {
  transfer_ownership: {
    amount: Uint128;
    to: string;
    token_id: number;
  };
} | {
  mint_smart_token: {
    amount: Uint128;
    to: string;
  };
} | {
  transfer_smart_token: {
    amount: Uint128;
    to: string;
  };
};
export type AssetType = "real_world_asset";
export type QueryMsg = {
  fractional_ownership: {
    owner: string;
    token_id: number;
  };
} | {
  token_u_r_i: {
    token_id: number;
  };
};
export type String = string;